In [2]:
import numpy as np
import copy
import matplotlib.pyplot as plt
import h5py
import scipy
from PIL import Image
from scipy import ndimage
import tensorflow as tf
%matplotlib inline
%load_ext autoreload
%autoreload 2

In [6]:
def load(f, label):
    # load the file into tensor
    image = tf.io.read_file(f)
    # Decode it to JPEG format
    image = tf.image.decode_jpeg(image)
    # Convert it to tf.float32
    image = tf.cast(image, tf.float32)

    return image, label

In [7]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# Flatten the matrix
flattened_matrix = matrix.flatten()

In [8]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
flattened_matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
X = matrix

In [11]:
X.shape[0]

3

In [12]:
X.reshape(X.shape[0], -1).T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [13]:
a, b, c, d = 2, 3, 4, 5
X = np.random.rand(a, b, c, d)

In [14]:
X

array([[[[0.83647007, 0.54345025, 0.98317891, 0.28240397, 0.45752501],
         [0.47562504, 0.29218591, 0.21866173, 0.88040239, 0.13684143],
         [0.72202886, 0.70735063, 0.97367758, 0.01078286, 0.06125984],
         [0.11822313, 0.66190365, 0.8722469 , 0.41621145, 0.21817997]],

        [[0.61038092, 0.25646633, 0.36004408, 0.77802752, 0.99290738],
         [0.0100632 , 0.55718854, 0.73233706, 0.06207454, 0.70883461],
         [0.77527149, 0.45201847, 0.19578817, 0.88736819, 0.11840845],
         [0.71183419, 0.04687759, 0.02341289, 0.9267236 , 0.50608916]],

        [[0.4262027 , 0.63661379, 0.89577634, 0.94782481, 0.47372172],
         [0.78255573, 0.83362004, 0.12240383, 0.40909868, 0.52688706],
         [0.76721448, 0.23062156, 0.0740437 , 0.03759242, 0.62934909],
         [0.57027414, 0.17347534, 0.03210952, 0.08649605, 0.67132784]]],


       [[[0.64138048, 0.67553662, 0.26967958, 0.34394274, 0.30409431],
         [0.18929805, 0.55877929, 0.1240349 , 0.68700435, 0.01164095]

In [15]:
X_flatten = X.reshape(b*c*d, a)


In [16]:
print("Original shape:", X.shape)
print("New shape:", X_flatten.shape)

Original shape: (2, 3, 4, 5)
New shape: (60, 2)


In [17]:
a

2

In [18]:
x = 64*64*3

In [19]:
X = np.array([[2, 3], [3, 4]])

In [20]:
X.reshape(4,1)


array([[2],
       [3],
       [3],
       [4]])

In [21]:
X[0]

array([2, 3])

In [22]:
w = X.reshape(X.shape[0], 1)

ValueError: cannot reshape array of size 4 into shape (2,1)

In [24]:
X.shape[0]

2

In [25]:
X.shape[0]

2

In [3]:

x = np.random.rand(4, 5)

y = np.sum(x, axis=1)

In [4]:
y

array([1.63792498, 2.81790982, 3.05685025, 2.12638273])

In [5]:
y.shape

(4,)