In [4]:
import numpy as np
import copy
import matplotlib.pyplot as plt
import h5py
import scipy
from PIL import Image
from scipy import ndimage
import tensorflow as tf
%matplotlib inline
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [5]:
def load(f, label):
    # load the file into tensor
    image = tf.io.read_file(f)
    # Decode it to JPEG format
    image = tf.image.decode_jpeg(image)
    # Convert it to tf.float32
    image = tf.cast(image, tf.float32)

    return image, label

In [7]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# Flatten the matrix
flattened_matrix = matrix.flatten()

In [8]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
flattened_matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
X = matrix

In [11]:
X.shape[0]

3

In [13]:
X.reshape(X.shape[0], -1).T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [14]:
a, b, c, d = 2, 3, 4, 5
X = np.random.rand(a, b, c, d)

In [15]:
X

array([[[[0.9105237 , 0.51773642, 0.25500268, 0.6218188 , 0.87043724],
         [0.86490469, 0.36742464, 0.49021675, 0.38596856, 0.02170086],
         [0.32622437, 0.18445956, 0.88469567, 0.01817139, 0.13732968],
         [0.06573756, 0.68608811, 0.16628707, 0.37663468, 0.59349687]],

        [[0.49114176, 0.95028524, 0.94696495, 0.74156456, 0.27016756],
         [0.91382915, 0.51813118, 0.44956681, 0.5609419 , 0.34625252],
         [0.13199312, 0.99692459, 0.93186919, 0.77052046, 0.76730283],
         [0.926881  , 0.87172144, 0.71560342, 0.19918387, 0.50306674]],

        [[0.94736882, 0.64811076, 0.23379534, 0.82388321, 0.17074152],
         [0.87170359, 0.5954767 , 0.09029114, 0.56520948, 0.11979588],
         [0.55169324, 0.00154427, 0.71326228, 0.60746187, 0.09414424],
         [0.61568917, 0.07720231, 0.29838599, 0.99659774, 0.62891649]]],


       [[[0.20820206, 0.13856097, 0.20482958, 0.6901437 , 0.89756769],
         [0.90839018, 0.79274901, 0.740405  , 0.02898209, 0.75647177]

In [16]:
X_flatten = X.reshape(b*c*d, a)


In [17]:
print("Original shape:", X.shape)
print("New shape:", X_flatten.shape)

Original shape: (2, 3, 4, 5)
New shape: (60, 2)


In [18]:
a

2