In [5]:
import numpy as np


In [6]:
a = np.random.rand(3,4)
a

array([[0.56862311, 0.24499072, 0.70619866, 0.15777481],
       [0.74284776, 0.57478818, 0.26209051, 0.11582942],
       [0.83686341, 0.96473674, 0.95611288, 0.0656956 ]])

In [7]:
b = np.random.rand(1, 4)
b


array([[0.80712719, 0.3736181 , 0.48017054, 0.65571065]])

In [8]:
c = a + b

In [9]:
c

array([[1.3757503 , 0.61860882, 1.1863692 , 0.81348546],
       [1.54997496, 0.94840628, 0.74226106, 0.77154007],
       [1.6439906 , 1.33835484, 1.43628342, 0.72140625]])

In [10]:
a = np.random.randn(1,3)
b = np.random.randn(3,3)

In [11]:
c = a*b
c

array([[ 0.22280305, -0.24295252,  0.25950365],
       [-0.19717168,  0.86951048,  0.41537464],
       [-0.23579969, -0.12843859, -2.37251213]])

In [12]:
a = np.array([[2, 1], [1,3]])

In [13]:
a

array([[2, 1],
       [1, 3]])

In [14]:
c

array([[ 0.22280305, -0.24295252,  0.25950365],
       [-0.19717168,  0.86951048,  0.41537464],
       [-0.23579969, -0.12843859, -2.37251213]])

In [15]:
a = np.array([[1,1], [1,-1]])
b = np.array([[2],[3]])


In [16]:
a

array([[ 1,  1],
       [ 1, -1]])

In [17]:
b

array([[2],
       [3]])

In [18]:
c = a+b

In [19]:
c

array([[3, 3],
       [4, 2]])

In [20]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [21]:
arr.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
a = np.array([[1, 2], [3, 4]])

In [23]:
a.reshape(1, -1)

array([[1, 2, 3, 4]])

In [24]:
a.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4]])

In [26]:
print(a.shape)

(2, 2)


In [29]:
dim = 3

In [30]:
w = np.zeros((dim, 1))


In [31]:
w

array([[0.],
       [0.],
       [0.]])

In [32]:
b = 0

In [33]:
# GRADED FUNCTION: predict

def predict(w, b, X):
    '''
    Predict whether the label is 0 or 1 using learned logistic regression parameters (w, b)

    Arguments:
    w -- weights, a numpy array of size (num_px * num_px * 3, 1)
    b -- bias, a scalar
    X -- data of size (num_px * num_px * 3, number of examples)

    Returns:
    Y_prediction -- a numpy array (vector) containing all predictions (0/1) for the examples in X
    '''

    m = X.shape[1]
    Y_prediction = np.zeros((1, m))
    w = w.reshape(X.shape[0], 1)

    # Compute vector "A" predicting the probabilities of a cat being present in the picture
    #(≈ 1 line of code)
    # A = ...
    # YOUR CODE STARTS HERE
    A = sigmoid(np.dot(w.T, X) + b)

    # YOUR CODE ENDS HERE

    for i in range(A.shape[1]):

        # Convert probabilities A[0,i] to actual predictions p[0,i]
        #(≈ 4 lines of code)
        # if A[0, i] > ____ :
        #     Y_prediction[0,i] =
        # else:
        #     Y_prediction[0,i] =
        # YOUR CODE STARTS HERE

        if A[0, i] > 0.5:
            Y_prediction[0,i] = 1
        else:
            Y_prediction[0,i] = 0

        # YOUR CODE ENDS HERE

    print(Y_prediction.shape)
    return Y_prediction