In [1]:
import numpy as np


In [2]:
a = np.random.rand(3,4)
a

array([[0.79149995, 0.26536273, 0.12206809, 0.40050179],
       [0.21629071, 0.43604389, 0.86404039, 0.84231887],
       [0.90153364, 0.46239381, 0.2273997 , 0.74266051]])

In [4]:
b = np.random.rand(1, 4)
b


array([[0.30531755, 0.62665034, 0.02957161, 0.36994731]])

In [5]:
c = a + b

In [6]:
c

array([[1.09681749, 0.89201307, 0.1516397 , 0.7704491 ],
       [0.52160826, 1.06269423, 0.893612  , 1.21226618],
       [1.20685118, 1.08904415, 0.25697131, 1.11260782]])

In [11]:
a = np.random.randn(1,3)
b = np.random.randn(3,3)

In [12]:
c = a*b
c

array([[-0.11128149, -0.3216228 ,  0.36428678],
       [ 0.39689448,  0.17102943, -0.80457366],
       [ 0.05867711, -0.12130218,  0.19507603]])

In [21]:
a = np.array([[2, 1], [1,3]])

In [22]:
a

array([[2, 1],
       [1, 3]])

In [23]:
c

array([[4, 1],
       [1, 9]])

In [26]:
a = np.array([[1,1], [1,-1]])
b = np.array([[2],[3]])


In [27]:
a

array([[ 1,  1],
       [ 1, -1]])

In [28]:
b

array([[2],
       [3]])

In [29]:
c = a+b

In [30]:
c

array([[3, 3],
       [4, 2]])

In [31]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [32]:
arr.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
a = np.array([[1, 2], [3, 4]])

In [36]:
a.reshape(1, -1)

array([[1, 2, 3, 4]])

In [37]:
a.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4]])